language: java

matrix:
  include:
    - os: linux
      jdk: oraclejdk8
    - os: linux
      jdk: oraclejdk7
    - os: linux
      jdk: openjdk7
    - os: osx

addons:
  sonarqube: true
  apt:
    sources:
      - sourceline: 'ppa:ubuntu-wine/ppa'
    packages:
      - wine1.7
      - lib32z1
      - lib32ncurses5

env:
  global:
    - secure: "K4OzI3bGQBzcQGUmNmlS9YdsG/IA7mFemP5QrlBCUkZ3Yj2DpQG4RijwNwyJQELhpj1VTtldgaqettOsY4+GtIfZHkf9nIdfSHg045LyVtc81U4cSdcjks6/HQ59jn3l2yjDnotFTTjhpFQj3ZYvamyXuOKEpjYzMR8+U6onX4V5TcWTZBYAwG1lQjrWzRIieJHGNZ33JGLVCT6FpYeAEeTqfY7GM/Cig9OGiVQ2MI4AhSwvPMTa4DB7UJSV4+n33e6AUt4TPFc5n92gguYG7jPhHfuEaZu1vd+eigCwEIaqi7erCjvi+qz0OAGhjlP7EorTze/II7HlfL1m5oN+98eU0snrua8DyPrBvXwVWD+8U3uenedhoAk6dwsV0JrZQtRyHD/hgX7ZhVzKuqrPqxHr2qT5+qomeQIUCZmn1tASsrvTNVbv9IFjit/FSKavi84livcYamoW/4SKevBP5NMMBTfigo9ftH/sdob6RD9jqLb1lqkEWbzrIjkkNF688iSdfkLGFhrfdju4tFQHuESAwUvJPH8Z97r+B8h5oeSysKYlj2ANLA1TbuCcKB2y7GK2B0nbsSWKrYAlM71w+0zpJ7CDVEFk0uHTIpPxGJfrCe3dIAS6JpGvob3ZrAh0E0WjcXJOWxNfeZ/ePMyyDxN+tzAdI4JhuqMyqFQGUyw="
    - JRE7_HOME=/usr/lib/jvm/java-7-oracle/jre

before_install:
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew install wine ant; fi;

script:
  - ant all
  - if [ "$TRAVIS_JDK_VERSION" == "oraclejdk8" ]; then sonar-scanner -Dsonar.login=$SONAR_TOKEN; fi;
